= Operační systémy (OSY)
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: A4
:icons: font

(C) Lukáš Kotek link:https://creativecommons.org/licenses/by-sa/4.0/[CC-BY-SA 4.0]

NOTE: Tento dokument nemá ambici v žádném slova smyslu suplovat technickou dokumentaci, odborné publikace nebo učebnice, které se komplexně zabývají problematikou operačních systémů a síťování. Je základní osnovou a rozcestníkem směřujícím na další materiály vytvořeným pro účely středoškolského předmětu _Operační systémy_. Předmět se zabývá problematikou operačních systémů obecně, základy správy MS Windows Serveru, posléze pak principy a použitím GNU/Linuxu, jeho konfigurací a nastavením jednotlivých síťových služeb.

<<<

== Podklady

. Operační systémy -- účel, rozdělení a typy jader [link:01-ucel-rozdeleni-jadra/01-ucel-rozdeleni-jadra.html[html]] [link:01-ucel-rozdeleni-jadra/01-ucel-rozdeleni-jadra.pdf[pdf]] [link:01-ucel-rozdeleni-jadra/01-ucel-rozdeleni-jadra.adoc[asciidoc]]

. TO DO :-)

